import { z } from 'zod';
export declare const TipoUbicacionSchema: z.ZodEnum<["MATRIZ", "FABRICA", "PUNTO_VENTA"]>;
export declare const CreateUbicacionSchema: z.ZodObject<{
    nombre: z.ZodString;
    tipo: z.ZodEnum<["MATRIZ", "FABRICA", "PUNTO_VENTA"]>;
    razon_social: z.ZodOptional<z.ZodString>;
    rfc: z.ZodOptional<z.ZodString>;
    regimen_fiscal: z.ZodOptional<z.ZodString>;
    calle: z.ZodOptional<z.ZodString>;
    num_ext: z.ZodOptional<z.ZodString>;
    num_int: z.ZodOptional<z.ZodString>;
    colonia: z.ZodOptional<z.ZodString>;
    municipio: z.ZodOptional<z.ZodString>;
    estado: z.ZodOptional<z.ZodString>;
    cp: z.ZodOptional<z.ZodString>;
    telefono: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    nombre: string;
    tipo: "MATRIZ" | "FABRICA" | "PUNTO_VENTA";
    razon_social?: string | undefined;
    rfc?: string | undefined;
    regimen_fiscal?: string | undefined;
    calle?: string | undefined;
    num_ext?: string | undefined;
    num_int?: string | undefined;
    colonia?: string | undefined;
    municipio?: string | undefined;
    estado?: string | undefined;
    cp?: string | undefined;
    telefono?: string | undefined;
}, {
    nombre: string;
    tipo: "MATRIZ" | "FABRICA" | "PUNTO_VENTA";
    razon_social?: string | undefined;
    rfc?: string | undefined;
    regimen_fiscal?: string | undefined;
    calle?: string | undefined;
    num_ext?: string | undefined;
    num_int?: string | undefined;
    colonia?: string | undefined;
    municipio?: string | undefined;
    estado?: string | undefined;
    cp?: string | undefined;
    telefono?: string | undefined;
}>;
export declare const UpdateUbicacionSchema: z.ZodObject<{
    nombre: z.ZodOptional<z.ZodString>;
    tipo: z.ZodOptional<z.ZodEnum<["MATRIZ", "FABRICA", "PUNTO_VENTA"]>>;
    razon_social: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    rfc: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    regimen_fiscal: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    calle: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    num_ext: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    num_int: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    colonia: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    municipio: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    estado: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    cp: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    telefono: z.ZodOptional<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    nombre?: string | undefined;
    razon_social?: string | undefined;
    rfc?: string | undefined;
    tipo?: "MATRIZ" | "FABRICA" | "PUNTO_VENTA" | undefined;
    regimen_fiscal?: string | undefined;
    calle?: string | undefined;
    num_ext?: string | undefined;
    num_int?: string | undefined;
    colonia?: string | undefined;
    municipio?: string | undefined;
    estado?: string | undefined;
    cp?: string | undefined;
    telefono?: string | undefined;
}, {
    nombre?: string | undefined;
    razon_social?: string | undefined;
    rfc?: string | undefined;
    tipo?: "MATRIZ" | "FABRICA" | "PUNTO_VENTA" | undefined;
    regimen_fiscal?: string | undefined;
    calle?: string | undefined;
    num_ext?: string | undefined;
    num_int?: string | undefined;
    colonia?: string | undefined;
    municipio?: string | undefined;
    estado?: string | undefined;
    cp?: string | undefined;
    telefono?: string | undefined;
}>;
export type TipoUbicacion = z.infer<typeof TipoUbicacionSchema>;
export type CreateUbicacionDto = z.infer<typeof CreateUbicacionSchema>;
export type UpdateUbicacionDto = z.infer<typeof UpdateUbicacionSchema>;
//# sourceMappingURL=ubicacion.schema.d.ts.map